// src/lib/data.js

export const commandResponsibilityData = [
  { id: 1, name: 'Abu Taleb', area: 'Dhanmondi', rank_n_zone: 'AC, Dhanmondi Zone', status: 'Transferred to Industrial Police', date: '04/09/24' },
  { id: 2, name: 'H M Azimul Haque', area: 'Mohamamdpur', rank_n_zone: 'DC, Tejgaon Division', status: 'Transferred to Office of the DIG, Rajshahi Range', date: '13/08/24' },
  { id: 3, name: 'Mr. M M Moinul Islam', area: 'Mirpur', rank_n_zone: 'ADC, Darus Salam Zone', status: 'Arrested', date: '28/01/25' },
  { id: 4, name: 'Mr. S. M. Shamim', area: 'Jatrabari', rank_n_zone: 'ADC, Wari Zone', status: 'Absconded from In-Service Training Center, Gaibandha', date: '18/09/24' },
  { id: 5, name: 'Mr. Golam Ruhani', area: 'Paltan', rank_n_zone: 'AC, Motijheel Zone', status: 'Absconded\nTemporarily suspended', date: '11/08/24' },
  { id: 6, name: 'Mr. Nazmul Hasan Firoz', area: 'Mirpur', rank_n_zone: 'ADC, Pallabi Zone', status: 'Transferred to APBn, Khagrachari', date: '27/08/24' },
  { id: 7, name: 'Mr. Masuk Mia PPM', area: 'Mirpur', rank_n_zone: 'ADC, Mirpur Zone', status: 'Transferred to Railway Police', date: '17/08/24' },
  { id: 8, name: 'Mr. Mithun Kumar Kundu', area: 'Paltan', rank_n_zone: 'AC, Patrol- Motijheel Zone', status: 'Transferred to RAB', date: '16/10/24' },
  { id: 9, name: 'Mr. Md. Ihsanul Firdaus', area: 'Dhanmondi', rank_n_zone: 'ADC, Dhanmondi Zone', status: 'Transferred to APBn', date: '27/08/24' },
  { id: 10, name: 'Mr. Md. Jasim Uddin Molla', area: 'Mirpur', rank_n_zone: 'DC, Mirpur Division', status: 'Arrested, Temporarily suspended', date: '30/10/24' },
  { id: 11, name: 'Mr. Md. Masudur Rahman Monir', area: 'Jatrabari', rank_n_zone: 'ADC, Demra Zone', status: 'Absconded from RAB, Barishal', date: '13/11/24' },
  { id: 12, name: 'Mr. Md. Rawshanul Haque Saikat', area: 'Mohamamdpur', rank_n_zone: 'ADC, Mohammadpur Zone', status: 'Absconded\nTemporarily suspended', date: '25/08/24' },
  { id: 13, name: 'Mr. Md. Rashedul Islam PPM', area: 'Rampura', rank_n_zone: 'ADC, Khilgaon Zone', status: 'Absconded from Barishal Metropolitan Police', date: '09/03/25' },
  { id: 14, name: 'Mr. Md. Shahidul Islam,', area: 'Rampura', rank_n_zone: 'ADC, PS&II', status: 'Transferred to In-Service Training Center, Cox\'s Bazar', date: '19/11/24' },
  { id: 15, name: 'Mr. Mohammad Alauddin', area: 'Jatrabari', rank_n_zone: 'ADC, Shyampur Zone', status: 'Transferred to APBn', date: '17/08/24' },
  { id: 16, name: 'Mr. Mohammad Imrul', area: 'Shahbagh', rank_n_zone: 'AC, Ramna Zone', status: 'Absconded from APBn', date: '28/01/25' },
  { id: 17, name: 'Mr. Mohammad Motiar Rahman', area: 'Mirpur', rank_n_zone: 'DC, POM-South Division', status: 'Transferred to PBI', date: '11/11/24' },
  { id: 18, name: 'Mr. Mohammad Ashraful Islam', area: 'Shahbagh', rank_n_zone: 'DC, Ramna Division', status: 'Office of the DIG, Rangpur Range', date: '13/08/24' },
  { id: 19, name: 'Mr. Rifat Rahman Shamim', area: 'Rampura', rank_n_zone: 'DC, Gulshan Division', status: 'Absconded', date: '06/08/24' },
  { id: 20, name: 'Mr. Refatul Islam Rifat', area: 'Dhanmondi', rank_n_zone: 'AC, New Market Zone', status: 'Transferred to APBn', date: '27/08/24' },
  { id: 21, name: 'Mr. Shahidul Islam', area: 'Mirpur', rank_n_zone: 'Senior AC, Pallabi Zone', status: 'Transferred to Industrial Police (Later in CID)\nPromoted', date: '04/09/24' },
  { id: 22, name: 'Mr. Shah Alam Md. Akhtarul Islam', area: 'Shahbagh', rank_n_zone: 'ADC, Ramna Zone', status: 'Absconded from In-Service Training Center, Sylhet', date: '26/01/25' },
  { id: 23, name: 'Mr. Satyaki Kabiraj Jhulon', area: 'Mirpur', rank_n_zone: 'ADC, POM North Division', status: 'Transferred to APBn\nPromoted', date: '30/09/24' },
  { id: 24, name: 'Mr. Sabbir Hasan', area: 'Rampura', rank_n_zone: 'AC, Khilgaon Zone', status: 'Transferred to Police Telecom Organization, Dhaka', date: '04/09/24' },
  { id: 25, name: 'Mr. Hafiz Al Asad', area: 'Dhanmondi', rank_n_zone: 'ADC, New Market Zone & Administration', status: 'Transferred to RAB', date: '27/08/24' },
  { id: 26, name: 'Mr. Hayatul Islam Khan', area: 'Rampura', rank_n_zone: 'DC, Motijheel Division', status: 'Transferred to Office of the DIG, Rajshahi Range', date: '13/08/24' },
  { id: 27, name: 'Mr. Hasan Muhammad Muhtarim', area: 'Mirpur', rank_n_zone: 'AC, Mirpur Zone', status: 'Transferred to RAB', date: '27/08/24' },
  { id: 28, name: 'Mr. Hasanuzzaman Molla', area: 'Rampura', rank_n_zone: 'ADC, Badda Zone', status: 'Absconded from APBn (Hill Tracts District)', date: '12/02/25' },
  { id: 29, name: 'Jahangir Hasan', area: 'Gulshan', rank_n_zone: 'ADC, Gulshan Zone', status: 'On a govt approved leave, never came back', date: '23/10/24' },
  { id: 30, name: 'Nahid Ferdous', area: 'Jatrabari', rank_n_zone: 'AC, Demra Zone', status: 'Transferred to RAB', date: '04/09/24' },
  { id: 31, name: 'Mizanur Rahman', area: 'Mohamamdpur', rank_n_zone: 'AC, Patrol-Mohammadpur Zone', status: 'Transferred to RAB', date: '04/09/24' },
  { id: 32, name: 'Mirza Salahuddin', area: 'Uttara', rank_n_zone: 'ADC, Uttara Zone', status: 'Absconded', date: '06/08/24' },
  { id: 33, name: 'Md. Azizul Haque', area: 'Mohamamdpur', rank_n_zone: 'AC, Mohammadpur Zone', status: 'Unknown', date: 'Unknown' },
  { id: 34, name: 'Md. Alamgir Hossain', area: 'Rampura', rank_n_zone: 'DC, PS&II', status: 'Transferred to River Police (Narayanganj)', date: '01/09/24' },
  { id: 35, name: 'Md. Ihsanul Firdaus', area: 'Dhanmondi', rank_n_zone: 'ADC, Dhanmondi Zone', status: 'Transferred to APBn', date: '27/08/24' },
  { id: 36, name: 'Md. Rakibul Hasan', area: 'Paltan', rank_n_zone: 'ADC, Motijheel Zone', status: 'Transferred to In-Service Training Center, Noakhali', date: '27/08/24' },
  { id: 37, name: 'Mohammad Iqbal Hossain', area: 'Jatrabari', rank_n_zone: 'DC, Wari Division', status: 'Absconded \nWas in DB custody on 20 August', date: '28/08/24' },
  { id: 38, name: 'Refatul Islam', area: 'Dhanmondi', rank_n_zone: 'AC, New Market Zone', status: 'Transferred to APBn', date: '27/08/24' },
  { id: 39, name: 'Shafiqul Islam', area: 'Mohakhali', rank_n_zone: 'AC, Gulshan Zone', status: 'Transferred to Railway Police', date: '04/09/24' },
  { id: 40, name: 'Shamsul Islam', area: 'Jatrabari', rank_n_zone: 'AC, Shyampur Zone', status: 'Transferred to RAB\nPromoted', date: '04/09/24' },
  { id: 41, name: 'Shah Alam Md. Akhtarul Islam', area: 'Dhanmondi', rank_n_zone: 'ADC, Ramna Zone', status: 'Absconded from In-Service Training Center, Sylhet', date: '26/01/25' },
  { id: 42, name: 'Sumon Kar', area: 'Uttara', rank_n_zone: 'AC, Uttara Zone', status: 'Transferred to APBn\nPromoted', date: '27/08/24' }
];